const popularSearchesTypes = {
    // GET_POPULAR_SEARCHES
    GET_POPULAR_SEARCHES_START: 'GET_POPULAR_SEARCHES_START',
    GET_POPULAR_SEARCHES_SUCCESS: 'GET_POPULAR_SEARCHES_SUCCESS',
    GET_POPULAR_SEARCHES_ERROR: 'GET_POPULAR_SEARCHES_ERROR',
};

export default popularSearchesTypes;
