const commentsTypes = {
    // GET_COMMENTS
    GET_COMMENTS_START: 'GET_COMMENTS_START',
    GET_COMMENTS_SUCCESS: 'GET_COMMENTS_SUCCESS',
    GET_COMMENTS_ERROR: 'GET_COMMENTS_ERROR',
    // CREATE_COMMENT
    CREATE_COMMENT_START: 'CREATE_COMMENT_START',
    CREATE_COMMENT_SUCCESS: 'CREATE_COMMENT_SUCCESS',
    CREATE_COMMENT_ERROR: 'CREATE_COMMENT_ERROR',
    // DELETE_COMMENT
    DELETE_COMMENT_START: 'DELETE_COMMENT_START',
    DELETE_COMMENT_SUCCESS: 'DELETE_COMMENT_SUCCESS',
    DELETE_COMMENT_ERROR: 'DELETE_COMMENT_ERROR',
    // REPLY_COMMENT
    REPLY_COMMENT_START: 'REPLY_COMMENT_START',
    REPLY_COMMENT_SUCCESS: 'REPLY_COMMENT_SUCCESS',
    REPLY_COMMENT_ERROR: 'REPLY_COMMENT_ERROR',
    // LIKE_COMMENT
    LIKE_COMMENT_START: 'LIKE_COMMENT_START',
    LIKE_COMMENT_SUCCESS: 'LIKE_COMMENT_SUCCESS',
    LIKE_COMMENT_ERROR: 'LIKE_COMMENT_ERROR',
    // DISLIKE_COMMENT
    DISLIKE_COMMENT_START: 'DISLIKE_COMMENT_START',
    DISLIKE_COMMENT_SUCCESS: 'DISLIKE_COMMENT_SUCCESS',
    DISLIKE_COMMENT_ERROR: 'DISLIKE_COMMENT_ERROR',
};

export default commentsTypes;
