#!/usr/bin/env node

"use strict";

const yargs = require('yargs');
const template = require('./lib/template')


const argv = yargs(process.argv.splice(2))
    .option('template', {
        alias: 't',
        description: 'Create new project from template',
        type: 'boolean'
    })
    .option('dir', {
        alias: 'd',
        description: 'Path to directory where to create a project',
        type: 'string'
    })
    .version().alias('version', 'v')
    .help().alias('help', 'h').argv;


if (argv.template) {
    return template();
}
