const chatTypes = {
    // TOGGLE_CHAT_DRAWER
    TOGGLE_CHAT_DRAWER: 'TOGGLE_CHAT_DRAWER',
    // CHANGE_CHAT_TYPE
    CHANGE_CHAT_TYPE: 'CHANGE_CHAT_TYPE',
    // GET_CHATS
    GET_CHATS_START: 'GET_CHATS_START',
    GET_CHATS_SUCCESS: 'GET_CHATS_SUCCESS',
    GET_CHATS_ERROR: 'GET_CHATS_ERROR',
    // REFRESH_CHATS
    REFRESH_CHATS_START: 'REFRESH_CHATS_START',
    REFRESH_CHATS_SUCCESS: 'REFRESH_CHATS_SUCCESS',
    REFRESH_CHATS_ERROR: 'REFRESH_CHATS_ERROR',
    // GET_CHATS
    GET_SINGLE_CHAT_START: 'GET_SINGLE_CHAT_START',
    GET_SINGLE_CHAT_SUCCESS: 'GET_SINGLE_CHAT_SUCCESS',
    GET_SINGLE_CHAT_ERROR: 'GET_SINGLE_CHAT_ERROR',
    // CREATE_CHAT
    CREATE_CHAT_START: 'CREATE_CHAT_START',
    CREATE_CHAT_SUCCESS: 'CREATE_CHAT_SUCCESS',
    CREATE_CHAT_ERROR: 'CREATE_CHAT_ERROR',
    // GET_MESSAGES
    GET_MESSAGES_START: 'GET_MESSAGES_START',
    GET_MESSAGES_SUCCESS: 'GET_MESSAGES_SUCCESS',
    GET_MESSAGES_ERROR: 'GET_MESSAGES_ERROR',
    // LOAD_MORE_MESSAGES
    LOAD_MORE_MESSAGES_START: 'LOAD_MORE_MESSAGES_START',
    LOAD_MORE_MESSAGES_SUCCESS: 'LOAD_MORE_MESSAGES_SUCCESS',
    LOAD_MORE_MESSAGES_ERROR: 'LOAD_MORE_MESSAGES_ERROR',
    // RECEIVE_MESSAGE
    RECEIVE_MESSAGE: 'RECEIVE_MESSAGE',
    // REMOVE_ALL_MESSAGES
    REMOVE_ALL_MESSAGES: 'REMOVE_ALL_MESSAGES',
    // GET_CHAT_OFFER_INFO
    GET_CHAT_OFFER_INFO_START: 'GET_CHAT_OFFER_INFO_START',
    GET_CHAT_OFFER_INFO_SUCCESS: 'GET_CHAT_OFFER_INFO_SUCCESS',
    GET_CHAT_OFFER_INFO_ERROR: 'GET_CHAT_OFFER_INFO_ERROR',
    // RESET_CHAT_SIDEBAR
    RESET_CHAT_SIDEBAR: 'RESET_CHAT_SIDEBAR',
};

export default chatTypes;
