# Generated by Django 3.1.2 on 2020-11-14 00:38

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ParentCategories',
            fields=[
                ('image', models.URLField()),
                ('is_active', models.BooleanField()),
                ('name', models.CharField(max_length=50)),
                ('priority', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)])),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'ordering': ['priority'],
            },
        ),
        migrations.CreateModel(
            name='ChildCategories',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('slug', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories', to='categories.parentcategories')),
            ],
        ),
    ]
