# Generated by Django 3.0.7 on 2020-09-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcategories',
            name='priority',
            field=models.IntegerField(),
        ),
    ]
