# Generated by Django 3.1.2 on 2020-11-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcategories',
            name='test_field',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
