# Generated by Django 2.1.5 on 2020-09-30 18:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('categories', '0002_auto_20200928_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='childcategories',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_categories',
                                    to='categories.ParentCategories'),
        ),
    ]
