# Generated by Django 2.1.5 on 2020-10-02 05:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('categories', '0003_auto_20200930_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parentcategories',
            name='priority',
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
