# Generated by Django 3.0.7 on 2020-10-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0004_auto_20201002_0530'),
    ]

    operations = [
        migrations.AddField(
            model_name='childcategories',
            name='slug',
            field=models.SlugField(default='super_unique_slag'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parentcategories',
            name='slug',
            field=models.SlugField(default='super_unique_slag_2'),
            preserve_default=False,
        ),
    ]
