const regionTypes = {
    // GET_COUNTRIES
    GET_COUNTRIES_START: 'GET_COUNTRIES_START',
    GET_COUNTRIES_SUCCESS: 'GET_COUNTRIES_SUCCESS',
    GET_COUNTRIES_ERROR: 'GET_COUNTRIES_ERROR',
    // GET_CITIES
    GET_CITIES_START: 'GET_CITIES_START',
    GET_CITIES_SUCCESS: 'GET_CITIES_SUCCESS',
    GET_CITIES_ERROR: 'GET_CITIES_ERROR',
    // OTHER
    SELECT_COUNTRY: 'SELECT_COUNTRY',
    SELECT_CITY: 'SELECT_CITY',
};

export default regionTypes;
