const profileTypes = {
    // GET_PUBLIC_PROFILE
    GET_PUBLIC_PROFILE_START: 'GET_PUBLIC_PROFILE_START',
    GET_PUBLIC_PROFILE_SUCCESS: 'GET_PUBLIC_PROFILE_SUCCESS',
    GET_PUBLIC_PROFILE_ERROR: 'GET_PUBLIC_PROFILE_ERROR',
};

export default profileTypes;
