# Generated by Django 3.1.2 on 2020-10-06 23:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar'), ('UAH', 'Hryvnia'), ('PLN', 'Złoty')], max_length=3)),
                ('deposit_needed', models.BooleanField()),
                ('deposit_val', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('doc_needed', models.BooleanField()),
                ('cover_image', models.URLField()),
                ('max_rent_per', models.CharField(choices=[('HOUR', 'Hour'), ('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month')], max_length=5)),
                ('min_rent_per', models.CharField(choices=[('HOUR', 'Hour'), ('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month')], max_length=5)),
                ('max_rent_value', models.SmallIntegerField()),
                ('min_rent_value', models.SmallIntegerField()),
                ('per', models.CharField(choices=[('HOUR', 'Hour'), ('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month')], max_length=5)),
                ('price', models.PositiveIntegerField()),
                ('promote_til_date', models.DateField(blank=True, null=True)),
                ('pud_date', models.DateField(auto_now=True)),
                ('extra_requirements', models.TextField(max_length=50)),
                ('status', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['pud_date'],
            },
        ),
        migrations.CreateModel(
            name='OfferImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='offers.offer')),
            ],
        ),
    ]
