# Generated by Django 3.1.2 on 2020-11-14 00:38

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('city', models.CharField(max_length=50)),
                ('cover_image', models.URLField()),
                ('currency', models.CharField(choices=[('EUR', 'Euro'), ('USD', 'Dollar'), ('UAH', 'Hryvnia'), ('PLN', 'Zloty')], max_length=3)),
                ('deposit_val', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('doc_needed', models.BooleanField()),
                ('extra_requirements', models.TextField(blank=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deliverable', models.BooleanField()),
                ('max_rent_per', models.CharField(blank=True, choices=[('HOUR', 'Hour'), ('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month')], max_length=5, null=True)),
                ('max_rent_value', models.SmallIntegerField(blank=True, null=True)),
                ('min_rent_per', models.CharField(blank=True, choices=[('HOUR', 'Hour'), ('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month')], max_length=5, null=True)),
                ('min_rent_value', models.SmallIntegerField(blank=True, null=True)),
                ('per', models.CharField(choices=[('HOUR', 'Hour'), ('DAY', 'Day'), ('WEEK', 'Week'), ('MONTH', 'Month')], max_length=5)),
                ('price', models.PositiveIntegerField()),
                ('promote_til_date', models.DateField(blank=True, null=True)),
                ('pud_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('INACTIVE', 'Inactive'), ('IN_RENT', 'In rent'), ('ARCHIVED', 'Archived'), ('FROZEN', 'Frozen')], default='DRAFT', max_length=8)),
                ('title', models.CharField(max_length=120)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['pud_date'],
            },
        ),
        migrations.CreateModel(
            name='OfferImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_images', to='offers.offer')),
            ],
        ),
    ]
