# Generated by Django 3.1.2 on 2020-10-07 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0002_auto_20201007_0908'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='categories.parentcategories'),
        ),
        migrations.AddField(
            model_name='offer',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='user_favourite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='sub_category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='categories.childcategories'),
        ),
    ]
