# Generated by Django 3.1.2 on 2020-10-07 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0002_auto_20201007_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='deposit_val',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
