# Generated by Django 3.1.2 on 2020-10-07 15:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0003_auto_20201007_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='favourite',
            field=models.ManyToManyField(blank=True, related_name='favourite_offers', to=settings.AUTH_USER_MODEL),
        ),
    ]
