# Generated by Django 3.1.2 on 2020-10-07 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0004_auto_20201007_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('REVIEW', 'Review'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived'), ('FROZEN', 'Frozen')], default='NEW', max_length=8),
        ),
    ]
