# Generated by Django 3.1.2 on 2021-01-13 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_remove_childcategories_test_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0005_auto_20201213_1424'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='max_rent',
            new_name='max_rent_period',
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='min_rent',
            new_name='mix_rent_period',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='max_rent_value',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='min_rent_value',
        ),
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='categories.parentcategories'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='cover_image',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='currency',
            field=models.CharField(blank=True, choices=[('EUR', 'Euro'), ('USD', 'Dollar'), ('UAH', 'Hryvnia'), ('PLN', 'Zloty')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='deposit_val',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='doc_needed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='favourite',
            field=models.ManyToManyField(blank=True, null=True, related_name='favourite_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='offer',
            name='is_deliverable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
