# Generated by Django 3.1.2 on 2020-10-17 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20201007_0908'),
        ('offers', '0006_auto_20201011_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.parentcategories'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('REVIEW', 'Review'), ('ACTIVE', 'Active'), ('REJECTED', 'Rejected'), ('INACTIVE', 'Inactive'), ('IN_RENT', 'In rent'), ('ARCHIVED', 'Archived'), ('FROZEN', 'Frozen')], default='DRAFT', max_length=8),
        ),
        migrations.AlterField(
            model_name='offer',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='categories.childcategories'),
        ),
    ]
