# Generated by Django 3.1.2 on 2020-10-17 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_auto_20201017_0944'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_deliverable',
            field=models.BooleanField(default=False),
        ),
    ]
