# Generated by Django 3.1.2 on 2021-01-13 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0007_auto_20210113_1513'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='mix_rent_period',
            new_name='min_rent_period',
        ),
    ]
