# Generated by Django 3.1.2 on 2021-01-14 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0008_auto_20210113_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offerimages',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_images', to='offers.offer'),
        ),
    ]
