# Generated by Django 3.1.2 on 2021-01-18 17:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0009_auto_20210114_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='favourite',
            field=models.ManyToManyField(blank=True, db_column='favourite', null=True, related_name='favourite_offers', to=settings.AUTH_USER_MODEL),
        ),
    ]
