# Generated by Django 3.1.2 on 2021-01-18 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_auto_20210118_1719'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='favourite',
            new_name='favorite',
        ),
    ]
