# Generated by Django 3.1.2 on 2020-10-17 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offers', '0010_auto_20201017_1017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='is_deliverable',
            field=models.BooleanField(),
        ),
    ]
