# Generated by Django 3.1.2 on 2021-01-18 17:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('offers', '0012_auto_20210118_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='favorite',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite_offers', to=settings.AUTH_USER_MODEL),
        ),
    ]
