const notificationsTypes = {
    // GET_NOTIFICATIONS
    GET_NOTIFICATIONS_START: 'GET_NOTIFICATIONS_START',
    GET_NOTIFICATIONS_SUCCESS: 'GET_NOTIFICATIONS_SUCCESS',
    GET_NOTIFICATIONS_ERROR: 'GET_NOTIFICATIONS_ERROR',
    // GET_NOTIFICATIONS_PAGINATION
    GET_NOTIFICATIONS_PAGINATION_START: 'GET_NOTIFICATIONS_PAGINATION_START',
    GET_NOTIFICATIONS_PAGINATION_SUCCESS: 'GET_NOTIFICATIONS_PAGINATION_SUCCESS',
    GET_NOTIFICATIONS_PAGINATION_ERROR: 'GET_NOTIFICATIONS_PAGINATION_ERROR',
    // DELETE_NOTIFICATION
    DELETE_NOTIFICATION_START: 'DELETE_NOTIFICATION_START',
    DELETE_NOTIFICATION_SUCCESS: 'DELETE_NOTIFICATION_SUCCESS',
    DELETE_NOTIFICATION_ERROR: 'DELETE_NOTIFICATION_ERROR',
};

export default notificationsTypes;
