# Generated by Django 3.1.2 on 2020-12-12 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userdislike_userlike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdislike',
            old_name='comment',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='userlike',
            old_name='comment',
            new_name='user',
        ),
    ]
